name: ZAP Baseline Scan

on:
  push:
    branches:
      - devtest3
  pull_request:
    branches:
      - devtest3

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    container:
      image: owasp/zap2docker-stable
      options: --shm-size=2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ZAP Baseline Scan
        run: |
          docker pull softwaresecurityproject/zap-stable
          docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable zap-baseline.py -t http://juice.hostdevtest.shop -r zap_report.html --auth-username admin@admin.com --auth-password admin
