apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: juiceshop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: juiceshop
spec:
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  #expose ip externo