FROM node:14.17.5-buster-slim
EXPOSE 3000
RUN npm i -g npm@6.14.14
ENV HOME=/home/app
COPY package.json  $HOME/webapp/
RUN chown -R app:app $HOME/*
USER app
WORKDIR $HOME/webapp
RUN npm i
USER root
COPY . $HOME/webapp
RUN chown -R app:app $HOME/*
USER app
CMD ["npm", "start"]