version: '3.8'

services:
  splunk:
    image: splunknbox/splunk_7.1.1:latest
    container_name: splunk
    ports:
      - "8000:8000"  # Porta para acessar a interface do Splunk
      - "8088:8088"  # Porta de recebimento de dados (HEC)
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=password
    networks:
      - observability

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "3001:3001"  # Porta em que a sua aplicação Flask está rodando
    networks:
      - observability
    depends_on:
      - splunk

networks:
  observability:
    driver: bridge