name: AWS Login

on:
  push:
    branches:
      - devtest2 

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencias
        run: |
               chmod +x install.sh
               ./install.sh       

      - name: Verify AWS CLI installation
        run: aws --version

      - name: Verify Python installation
        run: python --version
        
      - name: Verify Terraform
        run: terraform --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Install docker & docker-compose
        run: |
            sudo apt  install docker.io -y
            sudo apt  install docker-compose -y

      - name: install nodejs and NPM
        run: |
           sudo apt update -y
           sudo apt install nodejs -y
           sudo apt install npm -y
