version: '3.8'

services:
  express:
    build: 
      context: ./express_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - job2

networks:
  job2:
    driver: bridge