version: '3'
services:
  express:
    image: express_promethues:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    network_mode: "host"
  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    network_mode: "host"

  grafana:
    image: grafana/grafana
    ports:
    - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: "host"
volumes:
  grafana-data: