FROM node:18-alpine
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
RUN npm init -y
RUN npm install && npm install express
COPY package*.json ./
COPY . .
EXPOSE 3000
CMD [ "node", "server.js" ]