name: Cloud docker express app
on:
  push:
    branches:
      - "devtest2"
jobs:
  install:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
  
  express_deploy:
    needs: install
    runs-on: self-hosted
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Deploy Application using Docker Compose
      run: |
        cd express_app
        chmod +x .deploy.sh
        ./.deploy.sh