name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  script_vm:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install docker
        run: |
             sudo apt  install docker.io -y
             sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
             sudo chmod +x /usr/local/bin/docker-compose

      - name: Clone repository
        run: |
               sudo apt-get install git -y
               sudo git clone https://github.com/BrunoSantos88/Desenvolve-Trilha-SI.git

      - name: Checkout branch
        run: |
           git checkout devtest2

      - name: install nodejs and NPM
        run: |
           sudo apt update -y
           sudo apt install nodejs -y
           sudo apt install npm -y
    
     