name: Deploy Express_app

on:
  push:
    branches:
      - devtest2

jobs:
  express_vm:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Container && NodeJs and NPM
        run: |
         chmod +x dependencia.sh
         ./dependencia.sh
         echo "Install complete"

      - name: Clone repository
        run: |
               sudo apt-get install git -y
               sudo git clone https://github.com/BrunoSantos88/Desenvolve-Trilha-SI.git

      - name: Checkout branch && up app_express
        run: |
           git checkout devtest2
           cd express_app
           sudo docker-compose up -d   
           curl http://${{secrets.HOST_EXPRESS}}:3000
      


    
     