name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  ssh_command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -v

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install git -y

      - name: Clone repository
        run: git clone https://github.com/BrunoSantos88/Desenvolve-Trilha-SI.git

      - name: Checkout branch
        run: |
           git checkout devtest2
           sudo cd Desenvolve-Trilha-SI/ && git checkout devtest2 && cd express_app

      - name: Install NodeJs e NPM
        run: |
         sudo apt-get update -y
         sudo apt install curl -y
         sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
         sudo source ~/.bashrc
         sudo nvm install --lts
         sudo nvm alias default 24.1.2
         sudo node -v npm -v
         sudo npm init -y
         sudo npm install
         sudo npm install express
       
      - name: Install dependencias
        run: |
               sudo cd Desenvolve-Trilha-SI/ && git checkout devtest2 && cd express_app
               chmod +x install.sh
               ./install.sh     
               sudo docker --version
               sudo docker-compose --version
               sudo node --version
               sudo npm --version 
               sudo curl http//127.0.0.0:3000
