name: Push-to-EC2
on:
  push:
    branches:
      - devtest2
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Copy files to EC2 using SSH
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.SSH_EXPRESS_APP }}
          source: "./"
          target: "/home/ubuntu"
          server: ${{ secrets.REMOTE_HOST }}
          user: "ubuntu"
          remote-port: 22  # Specify the remote port
          args: "-rltgoDzvO"  # Additional SSH options