name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  ssh_command:
    runs-on: self-hosted

    steps:
      - name: Install Docker
        run: |
           sudo apt update -y
           sudo apt install docker.io -y
           sudo adduser $USER docker


      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo docker-compose -v

      - name: Verify Docker and Docker Compose installation
        run: |
          docker -v
          docker-compose -v