name: Deploy

on:
  push:
    branches: [ devtest2 ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key chmod 600 private_key

      - name: Execute SSH commands
        run: |
              sudo apt-get update
              sudo apt-get install -y docker.io