name: Deploy

on:
  push:
    branches: [ devtest2 ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.SSH_HOST}}
        USER_NAME: ${{secrets.USER_NAME}}
        script: |
            cd mkdir /home/ubuntu/app
            cd /home/ubuntu/app

