name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  ssh_command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencias
        run: |
               chmod +x install.sh
               ./install.sh       