name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  ssh_command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -v
       
      - name: Install dependencias
        run: |
               chmod +x install.sh
               ./install.sh     
               sudo docker --version
               sudo docker-compose --version
               sudo node --version
               sudo npm --version 
               sudo curl http//127.0.0.0:3000
