name: Deploy

on:
  push:
    branches: [ devtest2 ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.SSH_HOST}}
        USER_NAME: ${{secrets.USER_NAME}}
        run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key chmod 600 private_key

    - name: Install Docker and Node.js on EC2
      uses: appleboy/ssh-action@master
      with:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          run: |
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              sudo apt update
              sudo apt install -y docker.io
              sudo apt install -y nodejs npm

