name: Cloud docker express app
on:
  push:
    branches:
      - "devtest2"
jobs:
  install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test