name: Cloud docker express app
on:
  push:
    branches:
      - "devtest2"
jobs:
  install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: | 
              npm install

      - name: Run tests
        run: npm test

  express_deploy:
    needs: install
    runs-on: self-hosted
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node dependencies
      run: |
        cd desafio_docker_express/express_app
        npm install express

    - name: Deploy Application using Docker Compose
      run: |
        cd desafio_docker_express/express_app
        chmod +x express_deploy.sh
        ./express_deploy.sh