name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  script_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install git -y

      - name: Clone repository
        run: git clone https://github.com/BrunoSantos88/Desenvolve-Trilha-SI.git

      - name: Checkout branch
        run: |
           git checkout devtest2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Verify Node.js and npm installation
        run: |
          node -v
          npm -v
       
      - name: NPM commandos
        run: |
              sudo npm init -y
              sudo npm install
              sudo npm install express

      - name: NPM commandos
        run: |
              sudo npm init -y
              sudo npm install
              sudo npm install express

      - name: Install Docker && Compose
        run: |
          sudo apt-get install docker -y
          sudo adduser $USER docker
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -v
          cd express_app
          sudo docker-compose up -d
        
