name: AWS Login

on:
  push:
    branches:
      - devtest2 

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencias
        run: |
               chmod +x install.sh
               ./installl        

      - name: Verify AWS CLI installation
        run: aws --version

      - name: Verify Python installation
        run: python --version
        
      - name: Verify Terraform
        run: terraform --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region