name: Deploy

on:
  push:
    branches: [ devtest2 ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key chmod 600 private_key

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with the desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test