name: SSH Command

on:
  push:
    branches:
      - devtest2

jobs:
  script_vm:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install docker & docker-compose
        run: |
            sudo apt  install docker.io -y
            sudo apt  install docker-compose -y

      - name: install nodejs and NPM
        run: |
           sudo apt update -y
           sudo apt install nodejs -y
           sudo apt install npm -y

      - name: Clone repository
        run: |
               sudo apt-get install git -y
               sudo git clone https://github.com/BrunoSantos88/Desenvolve-Trilha-SI.git

      - name: Checkout branch && up app_express
        run: |
           git checkout devtest2
           cd express_app
           sudo docker-compose up -d   
      


    
     