name: Cloud docker express app
on:
  push:
    branches:
      - "devtest2"
jobs:
  install:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install nodejs 16
        run: | 
              chmod +x nodejs.sh
              ./nodejs.sh

      - name: Install docker && docker_compose
        run: | 
             chmod +x container.sh
             ./container.sh
