name: Deploy

on:
  push:
    branches: [ devtest2 ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key chmod 600 private_key

      - name: Clone Git repository
        run: |
          git clone https://github.com/BrunoSantos88/Desenvolve-Trilha-SI.git
          cd Desenvolve-Trilha-SI
          git switch devtest2
          chmod +x nodejs.sh
          ./nodejs.sh