name: desafio Deploy S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Optional
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION  # Optional

      - name: Install AWS CLI (optional, if not pre-installed on runner)
        run: |
          curl -sL https://raw.githubusercontent.com/aws/aws-cli/v2/installer/ubuntu/apt | sudo bash
          sudo apt install awscli -y

      - name: Build your project (replace with your build command)
        run: make build  # Replace with your build command

      - name: Upload files to S3 bucket
        run: |
          aws s3 cp --recursive build s3://your-bucket-name/path/in/bucket

      # Add other steps for deployment (e.g., invalidation of CloudFront cache)
