name: Deploy to Google bucket google cloud

on:
  push:
    branches:
      - main  # Substitua pela sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: desenvolve-alura
          service_account_key: ${{ secrets.GCLOUD_CREDENTIALS }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Storage
        run: |
          gsutil cp -r path/to/your/local/files gs://nome-do-seu-bucket
