name: Deploy to GCP Bucket

on:
  push:
    branches:
      - desafio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install dependencies and build
        run: |
          # Commands to install dependencies and build your project

      - name: Deploy to GCP Bucket
        run: |
          gsutil rsync -r . gs://desafioquiz
