name: Docker Image CI

on:
  push:
    branches: [ "desafio1" ]
  pull_request:
    branches: [ "desafio1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build . --file desafio_desenvolve_quiz/Dockerfile --tag my-quiz:$(date +%s)

      - name: Tag the Docker image
        run: |
          docker tag my-quiz:$(date +%s) my-quiz:latest

      - name: Push the Docker image
        run: |
          docker push my-quiz:$(date +%s)
          docker push my-quiz:latest
