name: Docker pipeline

on:
  push:
    branches:
      - "desafio2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          DOCKER_PASSWORD_STDIN: true

      - name: Docker BUILD
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./desafio_docker_express/express_app/Dockerfile
          tags: express_promethues:latest

      - name: Docker TAG AND PUSH
        run: |
         docker tag express_promethues:latest brunosantos88/express_prometheus
         docker push brunosantos88/express
