name: ci

on:
  push:
    branches:
      - "desafio2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          DOCKER_PASSWORD_STDIN: true

      - name: Docker BUILD
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./desafio_docker_express/Dockerfile
          tags: brunosantos/express:latest

      - name: Docker PUSH
        uses: docker/build-push-action@v5
        with:
        context: .
        push: true
        tags: brunosantos/express:latest