FROM nginx:latest

# Copy HTML, CSS, JavaScript, and images to nginx html directory
COPY ./index.html /usr/share/nginx/html/
COPY ./style.css /usr/share/nginx/html/
COPY ./index.js /usr/share/nginx/html/
COPY ./imagens /usr/share/nginx/html/images/

# Expose port 80 to make it accessible
EXPOSE 80

# Command to start nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
